modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/EngineHub/WorldEditCUI-Protocol/issues"
license = "EPL-2.0"

[[mods]]
modId = "worldeditcui_protocol"
version = "${version}"
displayName = "WorldEditCUI Protocol (NeoForge)"
authors = "EngineHub"
description = '''
Protocol implementation for the client-side user interface for WorldEdit
'''

[[dependencies.worldeditcui_protocol]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldeditcui_protocol]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"
